cache:
  directories:
    - $HOME/node_modules

language: node_js

node_js:
  - "4.1"
#   - "5"
#   - "0.12"
#   - "0.10"
#   - "iojs"

install:
  - npm -g install npm@latest-2
  - npm install

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev