os:
  - linux
  - osx

cache:
  directories:
    - node_modules
    - $HOME/.rvm
    - $HOME/.nvm

sudo: false

language: node_js

node_js:
  - "4.1"
#   - "5"
#   - "0.12"
#   - "0.10"
#   - "iojs"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pandoc  ; fi

install:
  - npm -g install npm@latest-2
  - npm install -g
  - npm install -g codeclimate-test-reporter package-json-validator
  - gem install travis github-pages

before_script:
  - which pandoc

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
      - pandoc
  code_climate:
      repo_token: b24eee69b925656c35879dd636cac1c382d5f07de0bd1c11b2197f9ec71c1d89

env:
  global:
    - GH_TOKEN=FAKE_TOKEN_FOR_TESTS