# Dependencies

markdown:         kramdown
# markdown:         redcarpet

# Permalinks
permalink:        pretty

# Setup
title:            Content as Code
tagline:          'Developing workflows and technology to improve content re-use and maintainability.'
description:      'Developing workflows and technology to improve content re-use and maintainability.'
url:              http://USER.github.io
baseurl:          /REPO

author:
  name:           'Your Name'
  url:            https://twitter.com/yourtwitter

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..3
  enable_coderay: false

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "lax_spacing", "smart"]

github:
  repo:           https://github.com/USER/REPO


gems:
  - jekyll-sitemap
  - jekyll-gist

# jekyll-travis

safe: false
lsi: false
pygments: true

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml